owner: bazziletech
repo: monitoring

sites:
  - name: Website
    url: https://www.bazzile.ch
  - name: APP
    url: https://www.bazzile.app
  - name: API
    url: https://www.bazzile.app/api
    method: POST
    body: '{"query": "{placesAutocomplete(query:\"Rue Charles-Galland\"){name}}","variables": {}}'
    headers:
      - "Content-Type: application/json"

assignees:
  - RoyalMist

status-website:
  cname: monitoring.bazzile.ch
  theme: light
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Bazzile Monitoring
  introTitle: "**Bazzile**, the new Real Estate Portal."
  introMessage: The status of our services are updated every 5 minutes.
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
