owner: bazziletech
repo: monitoring

assignees:
  - RoyalMist

sites:
  - name: Website
    url: https://www.bazzile.ch
  - name: APP
    url: https://www.bazzile.app
  - name: API
    url: https://www.bazzile.app/api
    method: POST
    body: '{"query": "{placesAutocomplete(query:\"Rue Charles-Galland\"){name}}","variables": {}}'
    headers:
      - "Content-Type: application/json"
   
status-website:
  cname: monitoring.bazzile.ch
  theme: night
  logoUrl: https://www.bazzile.app/images/logo-white-d060cc96813afc0aeefa402a06e5c2c7.svg?vsn=d
  name: Monitoring
  introTitle: "**Bazzile**, the new Real Estate Portal."
  introMessage: The status of our services are updated every 5 minutes and reflected here each day.
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://www.bazzile.ch
    - title: App
      href: https://www.bazzile.app
